### PR TITLE
Fewer rules, same performance

### PR DESCRIPTION
**Pull request by ghost**
Remove 815 rules that have no effect on the ruleset's performance.

Lifeboat - 2960729 cracks (as before)
Last.fm - 14634893 cracks (as before)

### CODE REVIEW

**Comment by stealthsploit** [comment]
I replicated and your revision produced the same on Lastfm, but one less, 2960728/4331053, on Lifeboat. Are you using the Skullsecurity variant of rockyou that has 14344391 candidates?

**Comment by ghost** [comment]
```
$ wc -l rockyou.txt.skullsecurity 
14344391 rockyou.txt.skullsecurity

$ sha1sum rockyou.txt.skullsecurity 
768abc17bafbce37bf3cf1e946f6d9970428b7b3  rockyou.txt.skullsecurity
```

Just rechecked.

```
Guess.Base.......: File (rockyou.txt.skullsecurity)
Recovered........: 2960729/4331053 (68.36%) Digests (total), 2960729/4331053 (68.36%) Digests (new)
Remaining........: 1370324 (31.64%) Digests
```

So it's probably our hashlists that are (still) subtly different. Mine is here: https://file.io/eWCiGHodHsiq

**Comment by stealthsploit** [comment]
Interesting, using your hash list I got the below using yours, 3 short. Our wordlists are the same. I'll have another look when I've got some more time.

`Recovered........: 2960726/4331053 (68.36%)`

**Comment by ghost** [comment]
Both hashcat 6.2.6 from hashcat.net and one manually built from the latest commit (`4d412c8e04dd972d1831aea8bead1a3b0cff3d8c`) give me the same number.

My command line:

```
./hashcat.bin --bitmap-max=26 --potfile-disable -o /dev/null -O -m 0 -r OneRuleToRuleThemStill.rule lifeboat_full.hash rockyou.txt.skullsecurity
```

```
$ wc -l OneRuleToRuleThemStill.rule
48439 OneRuleToRuleThemStill.rule

$ sha1sum OneRuleToRuleThemStill.rule
14ccc00bfbff1b8dc7c21a27d043c7307fe7c100  OneRuleToRuleThemStill.rule
```

**Pull request merged**
